service: serverless-recap

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: Jareer


functions:
  getUser:
    handler: lambdas/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: jarserverlessdemoprojectuploadbucket-28
      localDir: UploadData

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: jarserverlessdemoprojectuploadbucket-28
