service: serverless-recap

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  profile: Jareer


functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: jarserverlessdemoprojectuploadbucket-28
      localDir: UploadData

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: jarserverlessdemoprojectuploadbucket-28
